# Generated by Django 4.0.4 on 2022-04-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='bio',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
