# Generated by Django 4.0.4 on 2022-04-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_profil_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='korildi',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
